site_name: CivicEye
site_url: https://civiceye.streamlit.app/
repo_url: https://github.com/nicofirst1/CivicEye
repo_name: GitHub
nav:
  - Home: index.md
theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nicofirst1/CivicEye
